---
title: "About me"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Education and training

I am a student in p8105 at Columbia University Mailman School of Public Health.

My other prior education and training:

Brown University, BS - Neuroscience.

Mount Sinai School of Medicine, MD - Medical Doctorate.

Albert Einstein College of Medicine, MS - Clinical Research Methods.

Beth Israel Medical Center - Intern in Internal Medicine.

Mount Sinai Medical Center - Resident in Anesthesiology.

Lucile Packard Children's Hospital at Stanford University	- Fellow in Pediatric Anesthesiology.

# Personal Statement
My residency training and subsequent fellowship in pediatric anesthesiology allowed me to develop clinical expertise and a strong research interest in the effects of early anesthesia in infants and children. In addition, I completed a Masters Degree in Clinical Research Methods from my institutional NIH/CTSA-funded Clinical Research Training Program and recently earned a KL2 Mentored Career Development Award. My research focuses on clarifying the neurophysiologic effects of clinical anesthesia in human infants. In doing so, I hope to contribute to the knowledge of the brain response to clinical anesthesia early in human development. To this end, we are enrolling infants presenting for indicated general and spinal anesthesia and recording the full-head montage, unprocessed electroencephalogram (EEG). We already have a dataset of 54 infants receiving sevoflurane anesthesia and have published our preliminary analyses. We now have preliminary data in 25 infants receiving spinal anesthesia. The proposed research project aims to characterize the clinical sedation state associated with spinal anesthesia in early age and clarify its neurophysiologic correlates. We aim to: (i) recruit the entire sample size, (ii) record video-EEG before anesthesia and after spinal anesthesia administration, (iii) perform clinical-behavioral assessments of the sedated state using a validated, quantitative tool (the Pediatric Sedation State Scale), and (iv) analyze EEG data from this and age-matched controls during physiologic sleep and sevoflurane general anesthesia using power spectral analysis and other techniques. The results from this work will form the basis of future prospective studies of anesthesia during early age in a K23 application. My ultimate goal is to become an independent clinical investigator.

1.	Chao JY, Legatt AD, Yozawitz EG, Adams DC, Delphin ES, Shinnar S. Electroencephalographic Findings and Clinical Behavior During Induction of Anesthesia With Sevoflurane in Human Infants: A Prospective Observational Study. Anesth Analg. 2020 Jun;130(6):e161-e164. PubMed PMID: 31453873.

2.	Chao JY, Whitaker EE, Yozawitz EG, Legatt AL, Liu F, Walline M, Holmes G, Purdon PL, Shinnar S, Williams RK. Electroencephalographic Assessment of Sedation after Infant Spinal Anesthesia: A Multi-Center Pilot Study. American Society of Anesthesiologists (ASA) 2019 Annual Meeting Featured Abstract.

3.	Chao JY, Shinnar S, Legatt AD, Yozawitz EG, Delphin ES. Electroencephalographic findings and clinical behavior during induction of anesthesia with sevoflurane in infants. International Anesthesia Research Society (IARS) 2018 Annual Meeting Abstract.

4.	Andreae MH, Atchabahian A, McCrillis AM, Chao JY, Suzuki S, Shinnar S, Hall CB, Lipton RB. Regional versus General Anesthesia for Improved Cognitive Function after Procedures other than Cardiac Surgery or Neurosurgery in Adult and Paediatric Patients. Cochrane Database of Syst Rev. 2016;2016(6). Pii: CD008737. PMID:  27746701 PMCID: PMC5063242.

# Positions and Honors
## Positions and Employment

2006 - 2007	Intern in Internal Medicine, Beth Israel Medical Center, Albert Einstein College of Medicine

2007 - 2010	Resident in Anesthesiology, Mount Sinai Medical Center, Mount Sinai School of Medicine

2010 - 2011	Susan Packard Orr and Lynn Orr Clinical Fellow in Pediatric Anesthesiology, Lucile Packard Children's Hospital at Stanford University

2011 - 	Assistant Professor of Anesthesiology, Montefiore Medical Center, Albert Einstein College of Medicine
Other Experience and Professional Memberships

2011 - Present	Member, American Society of Anesthesiology

2011 - Present	Member, Society for Pediatric Anesthesiology

2011 - Present	Member, International Anesthesia Research Society

2011 - Present	Member, New York State Society of Anesthesiologists

2016 - Present	Member, Albert Einstein College of Medicine Institutional Review Board (IRB West)

## Honors

2013 - Clinical Teaching Award, Department of Anesthesiology, Albert Einstein College of Medicine, Montefiore Medical Center

2016 - Clinical Preceptor of the Year, Rutgers University School of Nurse Anesthesia

2019 - Junior Faculty Travel Award for Best Abstract in Pediatric Anesthesiology, Association of University Anesthesiologists

2019 - Featured Abstract, American Society of Anesthesiologists

2020 - Teaching Excellence, Leo M. Davidoff Society, Albert Einstein College of Medicine

2020 - Teaching Star Award, Albert Einstein College of Medicine

# Contribution to Science
During COVID, I led an observational study of pediatric patients admitted to our health system in the heart of the pandemic in New York City. The preliminary data from this study was published and led to a grant award funded by the Albert Einstein College of Medicine’s Dean’s Office to study the epidemiology of COVID-19 in pediatric patients. I have also authored a case report describing pediatric cerebellar mutism syndrome, an important complication after posterior fossa tumor resection. I have collaborated on quantitative reviews examining the role of regional anesthesia on cognitive function as well as persistent postoperative pain in adults and children published in the Cochrane Database of Systematic Reviews. I have authored a narrative review with collaborators examining the important role of simulation in pediatric sedation training.

1.	Chao JY, Derespina KR, Herold BC, Goldman DL, Aldrich M, Weingarten J, Ushay HM, Cabana MD, Medar SS. Clinical Characteristics and Outcomes of Hospitalized and Critically Ill Children and Adolescents with Coronavirus Disease 2019 at a Tertiary Care Medical Center in New York City. J Pediatr. 2020 Aug;223:14-19.e2. PubMed PMID: 32407719; PubMed Central PMCID: PMC7212947.

2.	Weinstein EJ, Levene JL, Cohen MS, Andreae DA, Chao JY, Johnson M, Hall CB, Andreae MH. Local anaesthetics and regional anaesthesia versus conventional analgesia for preventing persistent postoperative pain in adults and children. Cochrane Database Syst Rev. 2018 Jun 20;6:CD007105. PubMed PMID: 29926477; PubMed Central PMCID: PMC6377212. 

3.	Chao JY, Liu C, Shetty N, Shah U. Postoperative Pediatric Cerebellar Mutism After Posterior Fossa Surgery: A Case Report. A A Case Rep. 2017 Apr 15;8(8):213-215. PubMed PMID: 28118217; PubMed Central PMCID: PMC5391272. 
4.	Fehr JJ, Chao J, Kuan C, Zhong J. The important role of simulation in sedation. Curr Opin Anaesthesiol. 2016 Mar;29 Suppl 1:S14-20. PubMed PMID: 26926331. 

Complete List of Published Work in My Bibliography:
https://www.ncbi.nlm.nih.gov/myncbi/jerry.chao.1/bibliography/public/

# Additional Information: Research Support and/or Scholastic Performance

## Ongoing Research Support

#### KL2 TR002558, NIH/National Center for Advancing Translational Science (NCATS) Einstein-Montefiore Clinical and Translational Science Award

Chao (PI) 

08/01/20-07/31/22

Spinal Anesthesia in Human Infants: Behavioral and Electroencephalographic Assessment of Sedation

Role: PI

#### COVID-19 Micro-Grant, Albert Einstein College of Medicine, Dean's Office, Dr. Gordon Tomaselli

Chao (PI) 

06/01/20-06/01/21

Risk Factors Associated with Hospitalization Among Pediatric Patients with COVID-19 Infection

Role: PI