---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)

library(flexdashboard)
```

ny_noaa dataset

```{r}
data("ny_noaa")

ny_noaa_scatter =
ny_noaa %>% 
  sample_n(10000) %>% 
  separate(date, into = c("year", "month", "day")) %>% 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin),
    prcp = prcp / 10,
    tmax = tmax / 10,
    tmin = tmin / 10,
    prcp = as.integer(prcp),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin),
  ) %>% 
  group_by(id, year, month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) %>%
  filter(month %in% c(01, 07))

ny_noaa_bar =
ny_noaa %>% 
  sample_n(100) %>% 
  separate(date, into = c("year", "month", "day")) %>% 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin),
    prcp = prcp / 10,
    tmax = tmax / 10,
    tmin = tmin / 10,
    prcp = as.integer(prcp),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin),
  ) %>% 
  group_by(id, year, month) %>%  
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  )

ny_noaa_box =
ny_noaa %>% 
  sample_n(100) %>% 
  separate(date, into = c("year", "month", "day")) %>% 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin),
    prcp = prcp / 10,
    tmax = tmax / 10,
    tmin = tmin / 10,
    prcp = as.integer(prcp),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin),
  ) %>% 
  group_by(id, year, month) 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart A

```{r}
ny_noaa_scatter %>% 
  mutate(
    text_label = str_c("Station Id: ", id, "\nYear: ", year, "\nMonth: ", month)
  ) %>% 
  plot_ly(
    x = ~year, y = ~mean_tmax, text = ~text_label,
    alpha = .5, type = "scatter", mode = "markers"
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart B

```{r}
ny_noaa_box %>% 
  filter(tmax != "NA") %>% 
  mutate(
    tmax = as.factor(tmax),
    tmax = fct_relevel(tmax)
  ) %>% 
  plot_ly(
    y = ~tmax, x = ~id, color = ~id,
    type = "box", colors = "viridis"
  )
```

### Chart C

```{r}
ny_noaa_bar %>%
  filter(mean_tmax > 20) %>%
  count(mean_tmax) %>% 
  mutate(
    mean_tmax = as.factor(mean_tmax),
    mean_tmax = fct_reorder(mean_tmax, n)
  ) %>% 
  plot_ly(
    x = ~mean_tmax, y = ~n, color = ~id,
    type = "bar", colors = "viridis"
  )
```

