---
title: "Plotly examples"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Loading data

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

# Plotly plots

Using th ny_noaa dataset

## Scatterplot

```{r}
data("ny_noaa")

ny_noaa_scatter =
ny_noaa %>% 
  sample_n(10000) %>% 
  separate(date, into = c("year", "month", "day")) %>% 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin),
    prcp = prcp / 10,
    tmax = tmax / 10,
    tmin = tmin / 10,
    prcp = as.integer(prcp),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin),
  ) %>% 
  group_by(id, year, month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) %>%
  filter(month %in% c(01, 07))

ny_noaa_scatter %>% 
  mutate(
    text_label = str_c("Station Id: ", id, "\nYear: ", year, "\nMonth: ", month)
  ) %>% 
  plot_ly(
    x = ~year, y = ~mean_tmax, text = ~text_label,
    alpha = .5, type = "scatter", mode = "markers"
  )
```

## Bar plot

```{r}
ny_noaa_bar =
ny_noaa %>% 
  sample_n(100) %>% 
  separate(date, into = c("year", "month", "day")) %>% 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin),
    prcp = prcp / 10,
    tmax = tmax / 10,
    tmin = tmin / 10,
    prcp = as.integer(prcp),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin),
  ) %>% 
  group_by(id, year, month) %>%  
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) %>% 
  filter(mean_tmax != "NaN")
## how to get rid of duplicates  

ny_noaa_bar %>%
  filter(mean_tmax > 20) %>% 
  arrange(mean_tmax) %>% 
  plot_ly(
    x = ~year, y = ~mean_tmax,
    type = "bar"
  )
```

## Box plot

```{r}
ny_noaa_box =
ny_noaa %>% 
  sample_n(100) %>% 
  separate(date, into = c("year", "month", "day")) %>% 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin),
    prcp = prcp / 10,
    tmax = tmax / 10,
    tmin = tmin / 10,
    prcp = as.integer(prcp),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin),
  ) %>% 
  group_by(id, year, month) 

ny_noaa_box %>% 
  filter(tmax != "NA") %>%
  arrange(tmax) %>%
  count(tmax) %>% 
  mutate(
    tmax = as.factor(tmax),
    tmax = fct_relevel(tmax)
  ) %>% 
  plot_ly(
    y = ~tmax, x = ~id, color = ~id,
    type = "histogram", colors = "viridis"
  )
```